Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

새로운 크로스 플랫폼 PowerShell 사용 https://aka.ms/pscore6

PS C:\Users\schiz> ssh -i D:\Ddev\Key\devsacti-springboot2-webservice.pem ec2-user@ec2-54-180-177-202.ap-northeast-2.compute.amazonaws.com
Last login: Fri Jul 23 13:06:52 2021 from 210.205.132.131

       __|  __|_  )
       _|  (     /   Amazon Linux 2 AMI
      ___|\___|___|
Last login: Fri Jul 23 13:06:52 2021 from 210.205.132.131

       __|  __|_  )
       _|  (     /   Amazon Linux 2 AMI
      ___|\___|___|

https://aws.amazon.com/amazon-linux-2/
19 package(s) needed for security, out of 23 available
Run "sudo yum update" to apply all updates.
[ec2-user@devsacti-springboot2-webservice ~]$ pwd
/home/ec2-user
[ec2-user@devsacti-springboot2-webservice ~]$ ls
app  devsacti_django_webservice
[ec2-user@devsacti-springboot2-webservice ~]$ cd ..
[ec2-user@devsacti-springboot2-webservice home]$ ls
ec2-user
[ec2-user@devsacti-springboot2-webservice home]$ cd ..
[ec2-user@devsacti-springboot2-webservice /]$ ls
bin  boot  dev  etc  home  lib  lib64  local  media  mnt  opt  proc  root  run  sbin  srv  sys  tmp  usr  var
[ec2-user@devsacti-springboot2-webservice /]$ cd home
[ec2-user@devsacti-springboot2-webservice home]$ cd ec2-user
[ec2-user@devsacti-springboot2-webservice ~]$ ls
app  devsacti_django_webservice
[ec2-user@devsacti-springboot2-webservice ~]$ java --version
Unrecognized option: --version
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
[ec2-user@devsacti-springboot2-webservice ~]$ java -version
openjdk version "1.8.0_282"
OpenJDK Runtime Environment (build 1.8.0_282-b08)
OpenJDK 64-Bit Server VM (build 25.282-b08, mixed mode)
[ec2-user@devsacti-springboot2-webservice ~]$ ls
app  devsacti_django_webservice
[ec2-user@devsacti-springboot2-webservice ~]$ rm -rf devsacti_django_webservice
[ec2-user@devsacti-springboot2-webservice ~]$ ls
app
[ec2-user@devsacti-springboot2-webservice ~]$ cd app
[ec2-user@devsacti-springboot2-webservice app]$ ls
application-oauth.properties  application-real-db.properties  step1
[ec2-user@devsacti-springboot2-webservice app]$ cd ..
[ec2-user@devsacti-springboot2-webservice ~]$ ls
app
[ec2-user@devsacti-springboot2-webservice ~]$ mkdir django_app
[ec2-user@devsacti-springboot2-webservice ~]$ ls
app  django_app
[ec2-user@devsacti-springboot2-webservice ~]$ cd django_app
[ec2-user@devsacti-springboot2-webservice django_app]$ git clone https://github.com/aidsfintech/devsacti-django-webservice.git
Cloning into 'devsacti-django-webservice'...
remote: Enumerating objects: 9418, done.
remote: Counting objects: 100% (9418/9418), done.
remote: Compressing objects: 100% (6317/6317), done.
remote: Total 9418 (delta 2006), reused 9411 (delta 1999), pack-reused 0
Receiving objects: 100% (9418/9418), 34.12 MiB | 17.67 MiB/s, done.
Resolving deltas: 100% (2006/2006), done.
Updating files: 100% (7308/7308), done.
[ec2-user@devsacti-springboot2-webservice django_app]$ ls
devsacti-django-webservice
[ec2-user@devsacti-springboot2-webservice django_app]$ cd devsacti-django-webservice
[ec2-user@devsacti-springboot2-webservice devsacti-django-webservice]$ ls
devsacti_django  venv
[ec2-user@devsacti-springboot2-webservice devsacti-django-webservice]$ cd devsacti_django
[ec2-user@devsacti-springboot2-webservice devsacti_django]$ ls
config  dashboard  db.sqlite3  manage.py  myanalysis  scraping  static
[ec2-user@devsacti-springboot2-webservice devsacti_django]$ cd ~
[ec2-user@devsacti-springboot2-webservice ~]$ ls
app  django_app
[ec2-user@devsacti-springboot2-webservice ~]$ python --version
Python 2.7.18
[ec2-user@devsacti-springboot2-webservice ~]$ which python
/usr/bin/python
[ec2-user@devsacti-springboot2-webservice ~]$ ls /usr/bin/ | grep python
python
python2
python2.7
python2.7-config
python2-config
python3
python3.7
python3.7m
python-config
[ec2-user@devsacti-springboot2-webservice ~]$
[ec2-user@devsacti-springboot2-webservice ~]$
[ec2-user@devsacti-springboot2-webservice ~]$ sudo update-alternatives --config python
[ec2-user@devsacti-springboot2-webservice ~]$ update-alternatives --install /sur/bin/python python /usr/bin/python2.7 1
failed to create /var/lib/alternatives/python.new: Permission denied
[ec2-user@devsacti-springboot2-webservice ~]$ update-alternatives --install /usr/bin/python python /usr/bin/python2.7 1
failed to create /var/lib/alternatives/python.new: Permission denied


## core


[ec2-user@devsacti-springboot2-webservice ~]$ sudo update-alternatives --install /usr/bin/python python /usr/bin/python2.7 1
[ec2-user@devsacti-springboot2-webservice ~]$ sudo update-alternatives --install /usr/bin/python python /usr/bin/python3.7 2
[ec2-user@devsacti-springboot2-webservice ~]$ sudo update-alternatives --config python

There are 2 programs which provide 'python'.

  Selection    Command
-----------------------------------------------
   1           /usr/bin/python2.7
*+ 2           /usr/bin/python3.7

Enter to keep the current selection[+], or type selection number:
[ec2-user@devsacti-springboot2-webservice ~]$ python -V
Python 3.7.10
[ec2-user@devsacti-springboot2-webservice ~]$ ls
app  django_app
[ec2-user@devsacti-springboot2-webservice ~]$ cd django_app
[ec2-user@devsacti-springboot2-webservice django_app]$ ls
devsacti-django-webservice
[ec2-user@devsacti-springboot2-webservice django_app]$ cd devsacti-django-webservice
[ec2-user@devsacti-springboot2-webservice devsacti-django-webservice]$ ls
devsacti_django  venv
[ec2-user@devsacti-springboot2-webservice devsacti-django-webservice]$ source venv/bin/activate
-bash: venv/bin/activate: No such file or directory
[ec2-user@devsacti-springboot2-webservice devsacti-django-webservice]$ source venv/bin/activate
-bash: venv/bin/activate: No such file or directory
[ec2-user@devsacti-springboot2-webservice devsacti-django-webservice]$ cd venv
[ec2-user@devsacti-springboot2-webservice venv]$ ls
Lib  pyvenv.cfg  Scripts
[ec2-user@devsacti-springboot2-webservice venv]$ cd Lib
[ec2-user@devsacti-springboot2-webservice Lib]$ ls
site-packages
[ec2-user@devsacti-springboot2-webservice Lib]$ cd ..
[ec2-user@devsacti-springboot2-webservice venv]$ cd ..
[ec2-user@devsacti-springboot2-webservice devsacti-django-webservice]$ ls
devsacti_django  venv
[ec2-user@devsacti-springboot2-webservice devsacti-django-webservice]$ cd devsacti_django
[ec2-user@devsacti-springboot2-webservice devsacti_django]$ ls
config  dashboard  db.sqlite3  manage.py  myanalysis  scraping  static
[ec2-user@devsacti-springboot2-webservice devsacti_django]$ py manage.py runserver 0.0.0.0:8000
-bash: py: command not found
[ec2-user@devsacti-springboot2-webservice devsacti_django]$ python manage.py runserver 0.0.0.0:8000
Traceback (most recent call last):
  File "manage.py", line 11, in main
    from django.core.management import execute_from_command_line
ModuleNotFoundError: No module named 'django'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    main()
  File "manage.py", line 17, in main
    ) from exc
ImportError: Couldn't import Django. Are you sure it's installed and available on your PYTHONPATH environment variable? Did you forget to activate a virtual environment?
[ec2-user@devsacti-springboot2-webservice devsacti_django]$ ls
config  dashboard  db.sqlite3  manage.py  myanalysis  scraping  static
[ec2-user@devsacti-springboot2-webservice devsacti_django]$ cd ~
[ec2-user@devsacti-springboot2-webservice ~]$ ls
app  django_app


## core


[ec2-user@devsacti-springboot2-webservice ~]$ sudo pip3 install virtualenv
WARNING: Running pip install with root privileges is generally not a good idea. Try `pip3 install --user` instead.
Collecting virtualenv
  Downloading virtualenv-20.6.0-py2.py3-none-any.whl (5.3 MB)
     |████████████████████████████████| 5.3 MB 2.3 MB/s
Collecting six<2,>=1.9.0
  Downloading six-1.16.0-py2.py3-none-any.whl (11 kB)
Collecting platformdirs<3,>=2
  Downloading platformdirs-2.0.2-py2.py3-none-any.whl (10 kB)
Collecting distlib<1,>=0.3.1
  Downloading distlib-0.3.2-py2.py3-none-any.whl (338 kB)
     |████████████████████████████████| 338 kB 20.1 MB/s
Collecting filelock<4,>=3.0.0
  Downloading filelock-3.0.12-py3-none-any.whl (7.6 kB)
Collecting backports.entry-points-selectable>=1.0.4
  Downloading backports.entry_points_selectable-1.1.0-py2.py3-none-any.whl (6.2 kB)
Collecting importlib-metadata>=0.12; python_version < "3.8"
  Downloading importlib_metadata-4.6.1-py3-none-any.whl (17 kB)
Collecting zipp>=0.5
  Downloading zipp-3.5.0-py3-none-any.whl (5.7 kB)
Collecting typing-extensions>=3.6.4; python_version < "3.8"
  Downloading typing_extensions-3.10.0.0-py3-none-any.whl (26 kB)
Installing collected packages: six, platformdirs, distlib, filelock, zipp, typing-extensions, importlib-metadata, backports.entry-points-selectable, virtualenv
  WARNING: The script virtualenv is installed in '/usr/local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Successfully installed backports.entry-points-selectable-1.1.0 distlib-0.3.2 filelock-3.0.12 importlib-metadata-4.6.1 platformdirs-2.0.2 six-1.16.0 typing-extensions-3.10.0.0 virtualenv-20.6.0 zipp-3.5.0
[ec2-user@devsacti-springboot2-webservice ~]$ ls
app  django_app
[ec2-user@devsacti-springboot2-webservice ~]$ cd django_app
[ec2-user@devsacti-springboot2-webservice django_app]$ ls
devsacti-django-webservice
[ec2-user@devsacti-springboot2-webservice django_app]$ cd devsacti-django-webservice
[ec2-user@devsacti-springboot2-webservice devsacti-django-webservice]$ ls
devsacti_django  venv
[ec2-user@devsacti-springboot2-webservice devsacti-django-webservice]$ mv venv devsacti_django
[ec2-user@devsacti-springboot2-webservice devsacti-django-webservice]$ ls
devsacti_django
[ec2-user@devsacti-springboot2-webservice devsacti-django-webservice]$ cd devsact_django
-bash: cd: devsact_django: No such file or directory
[ec2-user@devsacti-springboot2-webservice devsacti-django-webservice]$ cd devsacti_django
[ec2-user@devsacti-springboot2-webservice devsacti_django]$ ls
config  dashboard  db.sqlite3  manage.py  myanalysis  scraping  static  venv
[ec2-user@devsacti-springboot2-webservice devsacti_django]$ python manage.py runserver 0.0.0.0:8000
Traceback (most recent call last):
  File "manage.py", line 11, in main
    from django.core.management import execute_from_command_line
ModuleNotFoundError: No module named 'django'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    main()
  File "manage.py", line 17, in main
    ) from exc
ImportError: Couldn't import Django. Are you sure it's installed and available on your PYTHONPATH environment variable? Did you forget to activate a virtual environment?
[ec2-user@devsacti-springboot2-webservice devsacti_django]$ cd ~
[ec2-user@devsacti-springboot2-webservice ~]$ ls
app  django_app
[ec2-user@devsacti-springboot2-webservice ~]$ cd django_app
[ec2-user@devsacti-springboot2-webservice django_app]$ ls
devsacti-django-webservice
[ec2-user@devsacti-springboot2-webservice django_app]$ cd devsacti-django-webservice
[ec2-user@devsacti-springboot2-webservice devsacti-django-webservice]$ ls
devsacti_django
[ec2-user@devsacti-springboot2-webservice devsacti-django-webservice]$ cd devsacti_django
[ec2-user@devsacti-springboot2-webservice devsacti_django]$ ls
config  dashboard  db.sqlite3  manage.py  myanalysis  scraping  static  venv


## core


[ec2-user@devsacti-springboot2-webservice devsacti_django]$ virtualenv myvenv
created virtual environment CPython3.7.10.final.0-64 in 964ms
  creator CPython3Posix(dest=/home/ec2-user/django_app/devsacti-django-webservice/devsacti_django/myvenv, clear=False, no_vcs_ignore=False, global=False)
  seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/home/ec2-user/.local/share/virtualenv)
    added seed packages: pip==21.1.3, setuptools==57.1.0, wheel==0.36.2
  activators BashActivator,CShellActivator,FishActivator,PowerShellActivator,PythonActivator,XonshActivator
[ec2-user@devsacti-springboot2-webservice devsacti_django]$ source newenv/bin/activate
-bash: newenv/bin/activate: No such file or directory
[ec2-user@devsacti-springboot2-webservice devsacti_django]$ ls
config  dashboard  db.sqlite3  manage.py  myanalysis  myvenv  scraping  static  venv
[ec2-user@devsacti-springboot2-webservice devsacti_django]$ ls
config  dashboard  db.sqlite3  manage.py  myanalysis  myvenv  scraping  static  venv
[ec2-user@devsacti-springboot2-webservice devsacti_django]$ source \newenvbin/activate
-bash: newenvbin/activate: No such file or directory
[ec2-user@devsacti-springboot2-webservice devsacti_django]$ source \newenvbinactivate
-bash: newenvbinactivate: No such file or directory
[ec2-user@devsacti-springboot2-webservice devsacti_django]$ source \newenv\bin\activate
-bash: newenvbinactivate: No such file or directory
[ec2-user@devsacti-springboot2-webservice devsacti_django]$ source /newenv/bin/activate
-bash: /newenv/bin/activate: No such file or directory
[ec2-user@devsacti-springboot2-webservice devsacti_django]$ cd ~
[ec2-user@devsacti-springboot2-webservice ~]$ ls
app  django_app
[ec2-user@devsacti-springboot2-webservice ~]$ python3 --version
Python 3.7.10
[ec2-user@devsacti-springboot2-webservice ~]$ pip3 --version
pip 20.2.2 from /usr/lib/python3.7/site-packages/pip (python 3.7)
[ec2-user@devsacti-springboot2-webservice ~]$ ls
app  django_app
[ec2-user@devsacti-springboot2-webservice ~]$ cd django_app
[ec2-user@devsacti-springboot2-webservice django_app]$ ls
devsacti-django-webservice
[ec2-user@devsacti-springboot2-webservice django_app]$ cd devsacti-django-webservice
[ec2-user@devsacti-springboot2-webservice devsacti-django-webservice]$ ls
devsacti_django
[ec2-user@devsacti-springboot2-webservice devsacti-django-webservice]$ cd devsacti_django
[ec2-user@devsacti-springboot2-webservice devsacti_django]$ ls
config  dashboard  db.sqlite3  manage.py  myanalysis  myvenv  scraping  static  venv
[ec2-user@devsacti-springboot2-webservice devsacti_django]$ rm -rf myvenv
[ec2-user@devsacti-springboot2-webservice devsacti_django]$ ls
config  dashboard  db.sqlite3  manage.py  myanalysis  scraping  static  venv


## core


[ec2-user@devsacti-springboot2-webservice devsacti_django]$ python3 -m virtualenv myvenv
created virtual environment CPython3.7.10.final.0-64 in 148ms
  creator CPython3Posix(dest=/home/ec2-user/django_app/devsacti-django-webservice/devsacti_django/myvenv, clear=False, no_vcs_ignore=False, global=False)
  seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/home/ec2-user/.local/share/virtualenv)
    added seed packages: pip==21.1.3, setuptools==57.1.0, wheel==0.36.2
  activators BashActivator,CShellActivator,FishActivator,PowerShellActivator,PythonActivator,XonshActivator
[ec2-user@devsacti-springboot2-webservice devsacti_django]$ ls
config  dashboard  db.sqlite3  manage.py  myanalysis  myvenv  scraping  static  venv
[ec2-user@devsacti-springboot2-webservice devsacti_django]$ pwd
/home/ec2-user/django_app/devsacti-django-webservice/devsacti_django
[ec2-user@devsacti-springboot2-webservice devsacti_django]$ source myvenv/bin/activate



## core


(myvenv) [ec2-user@devsacti-springboot2-webservice devsacti_django]$ pip3 install django==3.1
Collecting django==3.1
  Downloading Django-3.1-py3-none-any.whl (7.8 MB)
     |████████████████████████████████| 7.8 MB 1.7 MB/s
Collecting sqlparse>=0.2.2
  Downloading sqlparse-0.4.1-py3-none-any.whl (42 kB)
     |████████████████████████████████| 42 kB 2.0 MB/s
Collecting pytz
  Downloading pytz-2021.1-py2.py3-none-any.whl (510 kB)
     |████████████████████████████████| 510 kB 28.5 MB/s
Collecting asgiref~=3.2.10
  Downloading asgiref-3.2.10-py3-none-any.whl (19 kB)
Installing collected packages: sqlparse, pytz, asgiref, django
Successfully installed asgiref-3.2.10 django-3.1 pytz-2021.1 sqlparse-0.4.1
(myvenv) [ec2-user@devsacti-springboot2-webservice devsacti_django]$ ls
config  dashboard  db.sqlite3  manage.py  myanalysis  myvenv  scraping  static  venv
(myvenv) [ec2-user@devsacti-springboot2-webservice devsacti_django]$ python3 manage.py runserver 0.0.0.0:8000
Watching for file changes with StatReloader
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/usr/lib64/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ec2-user/django_app/devsacti-django-webservice/devsacti_django/myvenv/lib/python3.7/site-packages/django/utils/autoreload.py", line 53, in wrapper
    fn(*args, **kwargs)
  File "/home/ec2-user/django_app/devsacti-django-webservice/devsacti_django/myvenv/lib/python3.7/site-packages/django/core/management/commands/runserver.py", line 110, in inner_run
    autoreload.raise_last_exception()
  File "/home/ec2-user/django_app/devsacti-django-webservice/devsacti_django/myvenv/lib/python3.7/site-packages/django/utils/autoreload.py", line 76, in raise_last_exception
    raise _exception[1]
  File "/home/ec2-user/django_app/devsacti-django-webservice/devsacti_django/myvenv/lib/python3.7/site-packages/django/core/management/__init__.py", line 357, in execute
    autoreload.check_errors(django.setup)()
  File "/home/ec2-user/django_app/devsacti-django-webservice/devsacti_django/myvenv/lib/python3.7/site-packages/django/utils/autoreload.py", line 53, in wrapper
    fn(*args, **kwargs)
  File "/home/ec2-user/django_app/devsacti-django-webservice/devsacti_django/myvenv/lib/python3.7/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/ec2-user/django_app/devsacti-django-webservice/devsacti_django/myvenv/lib/python3.7/site-packages/django/apps/registry.py", line 114, in populate
    app_config.import_models()
  File "/home/ec2-user/django_app/devsacti-django-webservice/devsacti_django/myvenv/lib/python3.7/site-packages/django/apps/config.py", line 211, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib64/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ec2-user/django_app/devsacti-django-webservice/devsacti_django/scraping/models.py", line 5, in <module>
    class Naverstock(models.Model):
  File "/home/ec2-user/django_app/devsacti-django-webservice/devsacti_django/myvenv/lib/python3.7/site-packages/django/db/models/base.py", line 122, in __new__
    new_class.add_to_class('_meta', Options(meta, app_label))
  File "/home/ec2-user/django_app/devsacti-django-webservice/devsacti_django/myvenv/lib/python3.7/site-packages/django/db/models/base.py", line 326, in add_to_class
    value.contribute_to_class(cls, name)
  File "/home/ec2-user/django_app/devsacti-django-webservice/devsacti_django/myvenv/lib/python3.7/site-packages/django/db/models/options.py", line 206, in contribute_to_class
    self.db_table = truncate_name(self.db_table, connection.ops.max_name_length())
  File "/home/ec2-user/django_app/devsacti-django-webservice/devsacti_django/myvenv/lib/python3.7/site-packages/django/db/__init__.py", line 28, in __getattr__
    return getattr(connections[DEFAULT_DB_ALIAS], item)
  File "/home/ec2-user/django_app/devsacti-django-webservice/devsacti_django/myvenv/lib/python3.7/site-packages/django/db/utils.py", line 214, in __getitem__
    backend = load_backend(db['ENGINE'])
  File "/home/ec2-user/django_app/devsacti-django-webservice/devsacti_django/myvenv/lib/python3.7/site-packages/django/db/utils.py", line 111, in load_backend
    return import_module('%s.base' % backend_name)
  File "/usr/lib64/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ec2-user/django_app/devsacti-django-webservice/devsacti_django/myvenv/lib/python3.7/site-packages/django/db/backends/sqlite3/base.py", line 70, in <module>
    check_sqlite_version()
  File "/home/ec2-user/django_app/devsacti-django-webservice/devsacti_django/myvenv/lib/python3.7/site-packages/django/db/backends/sqlite3/base.py", line 67, in check_sqlite_version
    raise ImproperlyConfigured('SQLite 3.8.3 or later is required (found %s).' % Database.sqlite_version)
django.core.exceptions.ImproperlyConfigured: SQLite 3.8.3 or later is required (found 3.7.17).


^Z
[1]+  Stopped                 python3 manage.py runserver 0.0.0.0:8000
(myvenv) [ec2-user@devsacti-springboot2-webservice devsacti_django]$ ls
config  dashboard  db.sqlite3  manage.py  myanalysis  myvenv  scraping  static  venv
(myvenv) [ec2-user@devsacti-springboot2-webservice devsacti_django]$ ls
config  dashboard  db.sqlite3  manage.py  myanalysis  myvenv  scraping  static  venv
(myvenv) [ec2-user@devsacti-springboot2-webservice devsacti_django]$ django -V
-bash: django: command not found
(myvenv) [ec2-user@devsacti-springboot2-webservice devsacti_django]$ ls
config  dashboard  db.sqlite3  manage.py  myanalysis  myvenv  scraping  static  venv
(myvenv) [ec2-user@devsacti-springboot2-webservice devsacti_django]$ ls
config  dashboard  db.sqlite3  manage.py  myanalysis  myvenv  scraping  static  venv
(myvenv) [ec2-user@devsacti-springboot2-webservice devsacti_django]$ deactivate
[ec2-user@devsacti-springboot2-webservice devsacti_django]$ ls
config  dashboard  db.sqlite3  manage.py  myanalysis  myvenv  scraping  static  venv
[ec2-user@devsacti-springboot2-webservice devsacti_django]$ cd myvenv
[ec2-user@devsacti-springboot2-webservice myvenv]$ ls
bin  lib  lib64  pyvenv.cfg
[ec2-user@devsacti-springboot2-webservice myvenv]$ cd ..


## core



[ec2-user@devsacti-springboot2-webservice devsacti_django]$ source myvenv/bin/activate
(myvenv) [ec2-user@devsacti-springboot2-webservice devsacti_django]$ pip install django==2.1
Collecting django==2.1
  Downloading Django-2.1-py3-none-any.whl (7.3 MB)
     |████████████████████████████████| 7.3 MB 2.0 MB/s
Requirement already satisfied: pytz in ./myvenv/lib/python3.7/site-packages (from django==2.1) (2021.1)
Installing collected packages: django
  Attempting uninstall: django
    Found existing installation: Django 3.1
    Uninstalling Django-3.1:
      Successfully uninstalled Django-3.1
Successfully installed django-2.1
(myvenv) [ec2-user@devsacti-springboot2-webservice devsacti_django]$ ls
config  dashboard  db.sqlite3  manage.py  myanalysis  myvenv  scraping  static  venv
(myvenv) [ec2-user@devsacti-springboot2-webservice devsacti_django]$ python manage.py runserver 0.0.0.0:8000
Performing system checks...

System check identified some issues:

WARNINGS:
?: (urls.W005) URL namespace 'admin' isn't unique. You may not be able to reverse all URLs in this namespace

System check identified 1 issue (0 silenced).
July 23, 2021 - 06:32:15
Django version 2.1, using settings 'config.settings'
Starting development server at http://0.0.0.0:8000/
Quit the server with CONTROL-C.
^CTraceback (most recent call last):
  File "manage.py", line 22, in <module>
    main()
  File "manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/home/ec2-user/django_app/devsacti-django-webservice/devsacti_django/myvenv/lib/python3.7/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/home/ec2-user/django_app/devsacti-django-webservice/devsacti_django/myvenv/lib/python3.7/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/ec2-user/django_app/devsacti-django-webservice/devsacti_django/myvenv/lib/python3.7/site-packages/django/core/management/base.py", line 329, in run_from_argv
    connections.close_all()
  File "/home/ec2-user/django_app/devsacti-django-webservice/devsacti_django/myvenv/lib/python3.7/site-packages/django/db/utils.py", line 225, in close_all
    connection.close()
  File "/home/ec2-user/django_app/devsacti-django-webservice/devsacti_django/myvenv/lib/python3.7/site-packages/django/db/backends/sqlite3/base.py", line 190, in close
    if not self.is_in_memory_db():
  File "/home/ec2-user/django_app/devsacti-django-webservice/devsacti_django/myvenv/lib/python3.7/site-packages/django/db/backends/sqlite3/base.py", line 280, in is_in_memory_db
    return self.creation.is_in_memory_db(self.settings_dict['NAME'])
  File "/home/ec2-user/django_app/devsacti-django-webservice/devsacti_django/myvenv/lib/python3.7/site-packages/django/db/backends/sqlite3/creation.py", line 12, in is_in_memory_db
    return database_name == ':memory:' or 'mode=memory' in database_name
TypeError: argument of type 'PosixPath' is not iterable
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    main()
  File "manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/home/ec2-user/django_app/devsacti-django-webservice/devsacti_django/myvenv/lib/python3.7/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/home/ec2-user/django_app/devsacti-django-webservice/devsacti_django/myvenv/lib/python3.7/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/ec2-user/django_app/devsacti-django-webservice/devsacti_django/myvenv/lib/python3.7/site-packages/django/core/management/base.py", line 329, in run_from_argv
    connections.close_all()
  File "/home/ec2-user/django_app/devsacti-django-webservice/devsacti_django/myvenv/lib/python3.7/site-packages/django/db/utils.py", line 225, in close_all
    connection.close()
  File "/home/ec2-user/django_app/devsacti-django-webservice/devsacti_django/myvenv/lib/python3.7/site-packages/django/db/backends/sqlite3/base.py", line 190, in close
    if not self.is_in_memory_db():
  File "/home/ec2-user/django_app/devsacti-django-webservice/devsacti_django/myvenv/lib/python3.7/site-packages/django/db/backends/sqlite3/base.py", line 280, in is_in_memory_db
    return self.creation.is_in_memory_db(self.settings_dict['NAME'])
  File "/home/ec2-user/django_app/devsacti-django-webservice/devsacti_django/myvenv/lib/python3.7/site-packages/django/db/backends/sqlite3/creation.py", line 12, in is_in_memory_db
    return database_name == ':memory:' or 'mode=memory' in database_name
TypeError: argument of type 'PosixPath' is not iterable
(myvenv) [ec2-user@devsacti-springboot2-webservice devsacti_django]$
(myvenv) [ec2-user@devsacti-springboot2-webservice devsacti_django]$
(myvenv) [ec2-user@devsacti-springboot2-webservice devsacti_django]$ python manage.py runserver 8000
Performing system checks...

System check identified some issues:

WARNINGS:
?: (urls.W005) URL namespace 'admin' isn't unique. You may not be able to reverse all URLs in this namespace

System check identified 1 issue (0 silenced).
July 23, 2021 - 06:33:11
Django version 2.1, using settings 'config.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
^Z
[2]+  Stopped                 python manage.py runserver 8000
(myvenv) [ec2-user@devsacti-springboot2-webservice devsacti_django]$ ^C
(myvenv) [ec2-user@devsacti-springboot2-webservice devsacti_django]$
(myvenv) [ec2-user@devsacti-springboot2-webservice devsacti_django]$


## core



(myvenv) [ec2-user@devsacti-springboot2-webservice devsacti_django]$ python manage.py runserver 0.0.0.0:8000
Performing system checks...

System check identified some issues:

WARNINGS:
?: (urls.W005) URL namespace 'admin' isn't unique. You may not be able to reverse all URLs in this namespace

System check identified 1 issue (0 silenced).
July 23, 2021 - 06:37:53
Django version 2.1, using settings 'config.settings'
Starting development server at http://0.0.0.0:8000/
Quit the server with CONTROL-C.
Error: That port is already in use.
Traceback (most recent call last):
  File "/home/ec2-user/django_app/devsacti-django-webservice/devsacti_django/myvenv/lib/python3.7/site-packages/django/core/management/base.py", line 316, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/ec2-user/django_app/devsacti-django-webservice/devsacti_django/myvenv/lib/python3.7/site-packages/django/core/management/commands/runserver.py", line 60, in execute
    super().execute(*args, **options)
  File "/home/ec2-user/django_app/devsacti-django-webservice/devsacti_django/myvenv/lib/python3.7/site-packages/django/core/management/base.py", line 353, in execute
    output = self.handle(*args, **options)
  File "/home/ec2-user/django_app/devsacti-django-webservice/devsacti_django/myvenv/lib/python3.7/site-packages/django/core/management/commands/runserver.py", line 95, in handle
    self.run(**options)
  File "/home/ec2-user/django_app/devsacti-django-webservice/devsacti_django/myvenv/lib/python3.7/site-packages/django/core/management/commands/runserver.py", line 102, in run
    autoreload.main(self.inner_run, None, options)
  File "/home/ec2-user/django_app/devsacti-django-webservice/devsacti_django/myvenv/lib/python3.7/site-packages/django/utils/autoreload.py", line 323, in main
    python_reloader(wrapped_main_func, args, kwargs)
  File "/home/ec2-user/django_app/devsacti-django-webservice/devsacti_django/myvenv/lib/python3.7/site-packages/django/utils/autoreload.py", line 311, in python_reloader
    sys.exit(exit_code)
SystemExit: 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    main()
  File "manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/home/ec2-user/django_app/devsacti-django-webservice/devsacti_django/myvenv/lib/python3.7/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/home/ec2-user/django_app/devsacti-django-webservice/devsacti_django/myvenv/lib/python3.7/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/ec2-user/django_app/devsacti-django-webservice/devsacti_django/myvenv/lib/python3.7/site-packages/django/core/management/base.py", line 329, in run_from_argv
    connections.close_all()
  File "/home/ec2-user/django_app/devsacti-django-webservice/devsacti_django/myvenv/lib/python3.7/site-packages/django/db/utils.py", line 225, in close_all
    connection.close()
  File "/home/ec2-user/django_app/devsacti-django-webservice/devsacti_django/myvenv/lib/python3.7/site-packages/django/db/backends/sqlite3/base.py", line 190, in close
    if not self.is_in_memory_db():
  File "/home/ec2-user/django_app/devsacti-django-webservice/devsacti_django/myvenv/lib/python3.7/site-packages/django/db/backends/sqlite3/base.py", line 280, in is_in_memory_db
    return self.creation.is_in_memory_db(self.settings_dict['NAME'])
  File "/home/ec2-user/django_app/devsacti-django-webservice/devsacti_django/myvenv/lib/python3.7/site-packages/django/db/backends/sqlite3/creation.py", line 12, in is_in_memory_db
    return database_name == ':memory:' or 'mode=memory' in database_name
TypeError: argument of type 'PosixPath' is not iterable



## core



(myvenv) [ec2-user@devsacti-springboot2-webservice devsacti_django]$ sudo fuser -k 8000/tcp
8000/tcp:            15422
(myvenv) [ec2-user@devsacti-springboot2-webservice devsacti_django]$ python manage.py runserver 0.0.0.0:8000
Performing system checks...

System check identified some issues:

WARNINGS:
?: (urls.W005) URL namespace 'admin' isn't unique. You may not be able to reverse all URLs in this namespace

System check identified 1 issue (0 silenced).
July 23, 2021 - 06:39:22
Django version 2.1, using settings 'config.settings'
Starting development server at http://0.0.0.0:8000/
Quit the server with CONTROL-C.
[23/Jul/2021 06:39:47] "GET / HTTP/1.1" 200 50181
Not Found: /favicon.ico
[23/Jul/2021 06:39:47] "GET /favicon.ico HTTP/1.1" 404 3567
[23/Jul/2021 06:39:47] "GET / HTTP/1.1" 200 50181
[23/Jul/2021 06:39:47] "GET /static/css/styles.css HTTP/1.1" 404 1712
[23/Jul/2021 06:39:47] "GET /static/js/scripts.js HTTP/1.1" 404 1709
[23/Jul/2021 06:39:47] "GET /static/assets/demo/chart-area-demo.js HTTP/1.1" 404 1760
[23/Jul/2021 06:39:47] "GET /static/assets/demo/chart-bar-demo.js HTTP/1.1" 404 1757
[23/Jul/2021 06:39:47] "GET /static/js/datatables-simple-demo.js HTTP/1.1" 404 1754
[23/Jul/2021 06:39:48] "GET /static/js/scripts.js HTTP/1.1" 404 1709
[23/Jul/2021 06:39:48] "GET /static/assets/demo/chart-area-demo.js HTTP/1.1" 404 1760
[23/Jul/2021 06:39:48] "GET /static/assets/demo/chart-bar-demo.js HTTP/1.1" 404 1757
[23/Jul/2021 06:39:48] "GET /static/js/datatables-simple-demo.js HTTP/1.1" 404 1754
[23/Jul/2021 06:39:57] "GET /dashboard1 HTTP/1.1" 200 12502
[23/Jul/2021 06:39:57] "GET /static/css/styles.css HTTP/1.1" 404 1712
[23/Jul/2021 06:39:57] "GET /static/js/scripts.js HTTP/1.1" 404 1709
[23/Jul/2021 06:39:57] "GET /static/assets/demo/chart-area-demo.js HTTP/1.1" 404 1760
[23/Jul/2021 06:39:57] "GET /static/assets/demo/chart-bar-demo.js HTTP/1.1" 404 1757
[23/Jul/2021 06:39:57] "GET /static/js/datatables-simple-demo.js HTTP/1.1" 404 1754
[23/Jul/2021 06:39:57] "GET /static/js/scripts.js HTTP/1.1" 404 1709
[23/Jul/2021 06:39:57] "GET /static/assets/demo/chart-area-demo.js HTTP/1.1" 404 1760
[23/Jul/2021 06:39:57] "GET /static/assets/demo/chart-bar-demo.js HTTP/1.1" 404 1757
[23/Jul/2021 06:39:57] "GET /static/js/datatables-simple-demo.js HTTP/1.1" 404 1754
[23/Jul/2021 06:39:57] "GET /chart1 HTTP/1.1" 200 193